// Utility to convert OKLCH colors to hex format for html2canvas compatibility

// OKLCH to hex conversions for the color palette
export const colorConversions = {
  // Light mode colors
  '--background': '#ffffff',
  '--foreground': '#0f0f23',
  '--card': '#ffffff',
  '--card-foreground': '#0f0f23',
  '--popover': '#ffffff',
  '--popover-foreground': '#0f0f23',
  '--primary': '#2c2c47',
  '--primary-foreground': '#fafafa',
  '--secondary': '#f1f1f3',
  '--secondary-foreground': '#2c2c47',
  '--muted': '#f1f1f3',
  '--muted-foreground': '#717184',
  '--accent': '#f1f1f3',
  '--accent-foreground': '#2c2c47',
  '--destructive': '#dc2626',
  '--border': '#e4e4e8',
  '--input': '#e4e4e8',
  '--ring': '#94949e',
  '--chart-1': '#f59e0b',
  '--chart-2': '#06b6d4',
  '--chart-3': '#6366f1',
  '--chart-4': '#84cc16',
  '--chart-5': '#f97316',
  '--sidebar': '#fafafa',
  '--sidebar-foreground': '#0f0f23',
  '--sidebar-primary': '#2c2c47',
  '--sidebar-primary-foreground': '#fafafa',
  '--sidebar-accent': '#f1f1f3',
  '--sidebar-accent-foreground': '#2c2c47',
  '--sidebar-border': '#e4e4e8',
  '--sidebar-ring': '#94949e',

  // Dark mode colors
  '--background-dark': '#0f0f23',
  '--foreground-dark': '#fafafa',
  '--card-dark': '#2c2c47',
  '--card-foreground-dark': '#fafafa',
  '--popover-dark': '#2c2c47',
  '--popover-foreground-dark': '#fafafa',
  '--primary-dark': '#e4e4e8',
  '--primary-foreground-dark': '#2c2c47',
  '--secondary-dark': '#3c3c54',
  '--secondary-foreground-dark': '#fafafa',
  '--muted-dark': '#3c3c54',
  '--muted-foreground-dark': '#94949e',
  '--accent-dark': '#3c3c54',
  '--accent-foreground-dark': '#fafafa',
  '--destructive-dark': '#ef4444',
  '--border-dark': 'rgba(255, 255, 255, 0.1)',
  '--input-dark': 'rgba(255, 255, 255, 0.15)',
  '--ring-dark': '#717184',
  '--chart-1-dark': '#8b5cf6',
  '--chart-2-dark': '#10b981',
  '--chart-3-dark': '#f97316',
  '--chart-4-dark': '#a855f7',
  '--chart-5-dark': '#f43f5e',
  '--sidebar-dark': '#2c2c47',
  '--sidebar-foreground-dark': '#fafafa',
  '--sidebar-primary-dark': '#8b5cf6',
  '--sidebar-primary-foreground-dark': '#fafafa',
  '--sidebar-accent-dark': '#3c3c54',
  '--sidebar-accent-foreground-dark': '#fafafa',
  '--sidebar-border-dark': 'rgba(255, 255, 255, 0.1)',
  '--sidebar-ring-dark': '#717184'
};